### PR TITLE
Add issues tracker & discussion forums to explainer template

### PR DESCRIPTION
**Pull request by scheib**
Encourage explainer authors to facilitate participation and communication in their preferred forums.

### CODE REVIEW

**Comment by alice** [comment]
I like this. @cynthia @hober any thoughts?

**Comment by cynthia** [comment]
This makes sense. Thanks for the suggestion.

**Comment by scheib** [comment]
LGTMs from alice, cynthia, hober.  Let's land it?

**Comment by cynthia** [comment]
Done. Thanks!

**Pull request merged**
